// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[allow(unused_unsafe, clippy::all)]
/// Import runtime config functions (manually defined to match wasi:config/runtime@0.2.0-draft)
pub fn config_get(key: &str) -> Option<_rt::String> {
    unsafe {
        #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
        #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
        struct RetArea(
            [::core::mem::MaybeUninit<u8>; 3 * ::core::mem::size_of::<*const u8>()],
        );
        let mut ret_area = RetArea(
            [::core::mem::MaybeUninit::uninit(); 3 * ::core::mem::size_of::<*const u8>()],
        );
        let vec0 = key;
        let ptr0 = vec0.as_ptr().cast::<u8>();
        let len0 = vec0.len();
        let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "$root")]
        unsafe extern "C" {
            #[link_name = "config-get"]
            fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
        }
        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
            unreachable!()
        }
        unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
        let l3 = i32::from(*ptr1.add(0).cast::<u8>());
        let result7 = match l3 {
            0 => None,
            1 => {
                let e = {
                    let l4 = *ptr1
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l5 = *ptr1
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len6 = l5;
                    let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
                    _rt::string_lift(bytes6)
                };
                Some(e)
            }
            _ => _rt::invalid_enum_discriminant(),
        };
        result7
    }
}
#[allow(unused_unsafe, clippy::all)]
pub fn config_get_all() -> _rt::Vec<(_rt::String, _rt::String)> {
    unsafe {
        #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
        #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
        struct RetArea(
            [::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()],
        );
        let mut ret_area = RetArea(
            [::core::mem::MaybeUninit::uninit(); 2 * ::core::mem::size_of::<*const u8>()],
        );
        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "$root")]
        unsafe extern "C" {
            #[link_name = "config-get-all"]
            fn wit_import1(_: *mut u8);
        }
        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn wit_import1(_: *mut u8) {
            unreachable!()
        }
        unsafe { wit_import1(ptr0) };
        let l2 = *ptr0.add(0).cast::<*mut u8>();
        let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
        let base10 = l2;
        let len10 = l3;
        let mut result10 = _rt::Vec::with_capacity(len10);
        for i in 0..len10 {
            let base = base10.add(i * (4 * ::core::mem::size_of::<*const u8>()));
            let e10 = {
                let l4 = *base.add(0).cast::<*mut u8>();
                let l5 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len6 = l5;
                let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
                let l7 = *base
                    .add(2 * ::core::mem::size_of::<*const u8>())
                    .cast::<*mut u8>();
                let l8 = *base
                    .add(3 * ::core::mem::size_of::<*const u8>())
                    .cast::<usize>();
                let len9 = l8;
                let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);
                (_rt::string_lift(bytes6), _rt::string_lift(bytes9))
            };
            result10.push(e10);
        }
        _rt::cabi_dealloc(
            base10,
            len10 * (4 * ::core::mem::size_of::<*const u8>()),
            ::core::mem::size_of::<*const u8>(),
        );
        let result11 = result10;
        result11
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_test_get_config_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::test_get_config(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result1 {
        Ok(e) => {
            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
            let vec3 = (e.into_bytes()).into_boxed_slice();
            let ptr3 = vec3.as_ptr().cast::<u8>();
            let len3 = vec3.len();
            ::core::mem::forget(vec3);
            *ptr2.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
            *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr3
                .cast_mut();
        }
        Err(e) => {
            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
            let vec4 = (e.into_bytes()).into_boxed_slice();
            let ptr4 = vec4.as_ptr().cast::<u8>();
            let len4 = vec4.len();
            ::core::mem::forget(vec4);
            *ptr2.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
            *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4
                .cast_mut();
        }
    };
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_test_get_config<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
        }
        _ => {
            let l3 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l4 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l3, l4, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_test_get_all_config_cabi<T: Guest>() -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::test_get_all_config();
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result0 {
        Ok(e) => {
            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
            let vec2 = (e.into_bytes()).into_boxed_slice();
            let ptr2 = vec2.as_ptr().cast::<u8>();
            let len2 = vec2.len();
            ::core::mem::forget(vec2);
            *ptr1.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
            *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr2
                .cast_mut();
        }
        Err(e) => {
            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
            let vec3 = (e.into_bytes()).into_boxed_slice();
            let ptr3 = vec3.as_ptr().cast::<u8>();
            let len3 = vec3.len();
            ::core::mem::forget(vec3);
            *ptr1.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
            *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr3
                .cast_mut();
        }
    };
    ptr1
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_test_get_all_config<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
        }
        _ => {
            let l3 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l4 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l3, l4, 1);
        }
    }
}
pub trait Guest {
    /// Function that tests getting a specific config value
    /// Returns the value if found, or an error message
    fn test_get_config(key: _rt::String) -> Result<_rt::String, _rt::String>;
    /// Function that tests getting all config values
    /// Returns a comma-separated list of "key=value" pairs
    fn test_get_all_config() -> Result<_rt::String, _rt::String>;
}
#[doc(hidden)]
macro_rules! __export_world_root_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "test-get-config")] unsafe extern "C" fn
        export_test_get_config(arg0 : * mut u8, arg1 : usize,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_test_get_config_cabi::<$ty > (arg0, arg1) } }
        #[unsafe (export_name = "cabi_post_test-get-config")] unsafe extern "C" fn
        _post_return_test_get_config(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_test_get_config::<$ty > (arg0) } } #[unsafe (export_name =
        "test-get-all-config")] unsafe extern "C" fn export_test_get_all_config() -> *
        mut u8 { unsafe { $($path_to_types)*:: _export_test_get_all_config_cabi::<$ty >
        () } } #[unsafe (export_name = "cabi_post_test-get-all-config")] unsafe extern
        "C" fn _post_return_test_get_all_config(arg0 : * mut u8,) { unsafe {
        $($path_to_types)*:: __post_return_test_get_all_config::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_root_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 3 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 3 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_root_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_root_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_root_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:component:wasi-config-test:root:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 290] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xa7\x01\x01A\x02\x01\
A\x0c\x01ks\x01@\x01\x03keys\0\0\x03\0\x0aconfig-get\x01\x01\x01o\x02ss\x01p\x02\
\x01@\0\0\x03\x03\0\x0econfig-get-all\x01\x04\x01j\x01s\x01s\x01@\x01\x03keys\0\x05\
\x04\0\x0ftest-get-config\x01\x06\x01@\0\0\x05\x04\0\x13test-get-all-config\x01\x07\
\x04\0\x1fcomponent:wasi-config-test/root\x04\0\x0b\x0a\x01\0\x04root\x03\0\0\0G\
\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen\
-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
